/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as OrgOrgIdRouteImport } from './routes/org/$orgId'
import { Route as AppOrgIdRouteImport } from './routes/app/$orgId'
import { Route as ApiStorageAuthRouteImport } from './routes/api/storage-auth'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org/$orgId.index'
import { Route as AppOrgIdIndexRouteImport } from './routes/app/$orgId.index'
import { Route as OrgOrgIdWorkOrdersRouteImport } from './routes/org/$orgId.work-orders'
import { Route as OrgOrgIdSettingsRouteImport } from './routes/org/$orgId.settings'
import { Route as OrgOrgIdScheduleRouteImport } from './routes/org/$orgId.schedule'
import { Route as OrgOrgIdProceduresRouteImport } from './routes/org/$orgId.procedures_'
import { Route as OrgOrgIdPartsRouteImport } from './routes/org/$orgId.parts'
import { Route as OrgOrgIdLocationsRouteImport } from './routes/org/$orgId.locations'
import { Route as OrgOrgIdBusinessesRouteImport } from './routes/org/$orgId.businesses'
import { Route as OrgOrgIdAssetsRouteImport } from './routes/org/$orgId.assets'
import { Route as AppOrgIdSettingsRouteImport } from './routes/app/$orgId.settings'
import { Route as OrgOrgIdSettingsIndexRouteImport } from './routes/org/$orgId.settings.index'
import { Route as OrgOrgIdProceduresIndexRouteImport } from './routes/org/$orgId.procedures_.index'
import { Route as OrgOrgIdSettingsProfileRouteImport } from './routes/org/$orgId.settings.profile'
import { Route as OrgOrgIdSettingsOrganizationRouteImport } from './routes/org/$orgId.settings.organization'
import { Route as OrgOrgIdSettingsMembersRouteImport } from './routes/org/$orgId.settings.members'
import { Route as OrgOrgIdSettingsInvitationsRouteImport } from './routes/org/$orgId.settings.invitations'
import { Route as OrgOrgIdProceduresCreateRouteImport } from './routes/org/$orgId.procedures_.create'
import { Route as OrgOrgIdProceduresProcedureIdRouteImport } from './routes/org/$orgId.procedures_.$procedureId'
import { Route as AppOrgIdWorkOrdersWorkOrderIdRouteImport } from './routes/app/$orgId.work-orders.$workOrderId'
import { Route as AppOrgIdSettingsProfileRouteImport } from './routes/app/$orgId.settings_.profile'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgIdRoute = AppOrgIdRouteImport.update({
  id: '/app/$orgId',
  path: '/app/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageAuthRoute = ApiStorageAuthRouteImport.update({
  id: '/api/storage-auth',
  path: '/api/storage-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const AppOrgIdIndexRoute = AppOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgIdRoute,
} as any)
const OrgOrgIdWorkOrdersRoute = OrgOrgIdWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsRoute = OrgOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdScheduleRoute = OrgOrgIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdProceduresRoute = OrgOrgIdProceduresRouteImport.update({
  id: '/procedures_',
  path: '/procedures',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdPartsRoute = OrgOrgIdPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdLocationsRoute = OrgOrgIdLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdBusinessesRoute = OrgOrgIdBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdAssetsRoute = OrgOrgIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const AppOrgIdSettingsRoute = AppOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgIdRoute,
} as any)
const OrgOrgIdSettingsIndexRoute = OrgOrgIdSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdProceduresIndexRoute = OrgOrgIdProceduresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdProceduresRoute,
} as any)
const OrgOrgIdSettingsProfileRoute = OrgOrgIdSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsOrganizationRoute =
  OrgOrgIdSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsMembersRoute = OrgOrgIdSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsInvitationsRoute =
  OrgOrgIdSettingsInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdProceduresCreateRoute =
  OrgOrgIdProceduresCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => OrgOrgIdProceduresRoute,
  } as any)
const OrgOrgIdProceduresProcedureIdRoute =
  OrgOrgIdProceduresProcedureIdRouteImport.update({
    id: '/$procedureId',
    path: '/$procedureId',
    getParentRoute: () => OrgOrgIdProceduresRoute,
  } as any)
const AppOrgIdWorkOrdersWorkOrderIdRoute =
  AppOrgIdWorkOrdersWorkOrderIdRouteImport.update({
    id: '/work-orders/$workOrderId',
    path: '/work-orders/$workOrderId',
    getParentRoute: () => AppOrgIdRoute,
  } as any)
const AppOrgIdSettingsProfileRoute = AppOrgIdSettingsProfileRouteImport.update({
  id: '/settings_/profile',
  path: '/settings/profile',
  getParentRoute: () => AppOrgIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storage-auth': typeof ApiStorageAuthRoute
  '/app/$orgId': typeof AppOrgIdRouteWithChildren
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$orgId/settings': typeof AppOrgIdSettingsRoute
  '/org/$orgId/assets': typeof OrgOrgIdAssetsRoute
  '/org/$orgId/businesses': typeof OrgOrgIdBusinessesRoute
  '/org/$orgId/locations': typeof OrgOrgIdLocationsRoute
  '/org/$orgId/parts': typeof OrgOrgIdPartsRoute
  '/org/$orgId/procedures': typeof OrgOrgIdProceduresRouteWithChildren
  '/org/$orgId/schedule': typeof OrgOrgIdScheduleRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/work-orders': typeof OrgOrgIdWorkOrdersRoute
  '/app/$orgId/': typeof AppOrgIdIndexRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/app/$orgId/settings/profile': typeof AppOrgIdSettingsProfileRoute
  '/app/$orgId/work-orders/$workOrderId': typeof AppOrgIdWorkOrdersWorkOrderIdRoute
  '/org/$orgId/procedures/$procedureId': typeof OrgOrgIdProceduresProcedureIdRoute
  '/org/$orgId/procedures/create': typeof OrgOrgIdProceduresCreateRoute
  '/org/$orgId/settings/invitations': typeof OrgOrgIdSettingsInvitationsRoute
  '/org/$orgId/settings/members': typeof OrgOrgIdSettingsMembersRoute
  '/org/$orgId/settings/organization': typeof OrgOrgIdSettingsOrganizationRoute
  '/org/$orgId/settings/profile': typeof OrgOrgIdSettingsProfileRoute
  '/org/$orgId/procedures/': typeof OrgOrgIdProceduresIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storage-auth': typeof ApiStorageAuthRoute
  '/app': typeof AppIndexRoute
  '/app/$orgId/settings': typeof AppOrgIdSettingsRoute
  '/org/$orgId/assets': typeof OrgOrgIdAssetsRoute
  '/org/$orgId/businesses': typeof OrgOrgIdBusinessesRoute
  '/org/$orgId/locations': typeof OrgOrgIdLocationsRoute
  '/org/$orgId/parts': typeof OrgOrgIdPartsRoute
  '/org/$orgId/schedule': typeof OrgOrgIdScheduleRoute
  '/org/$orgId/work-orders': typeof OrgOrgIdWorkOrdersRoute
  '/app/$orgId': typeof AppOrgIdIndexRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/app/$orgId/settings/profile': typeof AppOrgIdSettingsProfileRoute
  '/app/$orgId/work-orders/$workOrderId': typeof AppOrgIdWorkOrdersWorkOrderIdRoute
  '/org/$orgId/procedures/$procedureId': typeof OrgOrgIdProceduresProcedureIdRoute
  '/org/$orgId/procedures/create': typeof OrgOrgIdProceduresCreateRoute
  '/org/$orgId/settings/invitations': typeof OrgOrgIdSettingsInvitationsRoute
  '/org/$orgId/settings/members': typeof OrgOrgIdSettingsMembersRoute
  '/org/$orgId/settings/organization': typeof OrgOrgIdSettingsOrganizationRoute
  '/org/$orgId/settings/profile': typeof OrgOrgIdSettingsProfileRoute
  '/org/$orgId/procedures': typeof OrgOrgIdProceduresIndexRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storage-auth': typeof ApiStorageAuthRoute
  '/app/$orgId': typeof AppOrgIdRouteWithChildren
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$orgId/settings': typeof AppOrgIdSettingsRoute
  '/org/$orgId/assets': typeof OrgOrgIdAssetsRoute
  '/org/$orgId/businesses': typeof OrgOrgIdBusinessesRoute
  '/org/$orgId/locations': typeof OrgOrgIdLocationsRoute
  '/org/$orgId/parts': typeof OrgOrgIdPartsRoute
  '/org/$orgId/procedures_': typeof OrgOrgIdProceduresRouteWithChildren
  '/org/$orgId/schedule': typeof OrgOrgIdScheduleRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/work-orders': typeof OrgOrgIdWorkOrdersRoute
  '/app/$orgId/': typeof AppOrgIdIndexRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/app/$orgId/settings_/profile': typeof AppOrgIdSettingsProfileRoute
  '/app/$orgId/work-orders/$workOrderId': typeof AppOrgIdWorkOrdersWorkOrderIdRoute
  '/org/$orgId/procedures_/$procedureId': typeof OrgOrgIdProceduresProcedureIdRoute
  '/org/$orgId/procedures_/create': typeof OrgOrgIdProceduresCreateRoute
  '/org/$orgId/settings/invitations': typeof OrgOrgIdSettingsInvitationsRoute
  '/org/$orgId/settings/members': typeof OrgOrgIdSettingsMembersRoute
  '/org/$orgId/settings/organization': typeof OrgOrgIdSettingsOrganizationRoute
  '/org/$orgId/settings/profile': typeof OrgOrgIdSettingsProfileRoute
  '/org/$orgId/procedures_/': typeof OrgOrgIdProceduresIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/select-organization'
    | '/signup'
    | '/terms'
    | '/api/health'
    | '/api/storage-auth'
    | '/app/$orgId'
    | '/org/$orgId'
    | '/app/'
    | '/app/$orgId/settings'
    | '/org/$orgId/assets'
    | '/org/$orgId/businesses'
    | '/org/$orgId/locations'
    | '/org/$orgId/parts'
    | '/org/$orgId/procedures'
    | '/org/$orgId/schedule'
    | '/org/$orgId/settings'
    | '/org/$orgId/work-orders'
    | '/app/$orgId/'
    | '/org/$orgId/'
    | '/app/$orgId/settings/profile'
    | '/app/$orgId/work-orders/$workOrderId'
    | '/org/$orgId/procedures/$procedureId'
    | '/org/$orgId/procedures/create'
    | '/org/$orgId/settings/invitations'
    | '/org/$orgId/settings/members'
    | '/org/$orgId/settings/organization'
    | '/org/$orgId/settings/profile'
    | '/org/$orgId/procedures/'
    | '/org/$orgId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/select-organization'
    | '/signup'
    | '/terms'
    | '/api/health'
    | '/api/storage-auth'
    | '/app'
    | '/app/$orgId/settings'
    | '/org/$orgId/assets'
    | '/org/$orgId/businesses'
    | '/org/$orgId/locations'
    | '/org/$orgId/parts'
    | '/org/$orgId/schedule'
    | '/org/$orgId/work-orders'
    | '/app/$orgId'
    | '/org/$orgId'
    | '/app/$orgId/settings/profile'
    | '/app/$orgId/work-orders/$workOrderId'
    | '/org/$orgId/procedures/$procedureId'
    | '/org/$orgId/procedures/create'
    | '/org/$orgId/settings/invitations'
    | '/org/$orgId/settings/members'
    | '/org/$orgId/settings/organization'
    | '/org/$orgId/settings/profile'
    | '/org/$orgId/procedures'
    | '/org/$orgId/settings'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/select-organization'
    | '/signup'
    | '/terms'
    | '/api/health'
    | '/api/storage-auth'
    | '/app/$orgId'
    | '/org/$orgId'
    | '/app/'
    | '/app/$orgId/settings'
    | '/org/$orgId/assets'
    | '/org/$orgId/businesses'
    | '/org/$orgId/locations'
    | '/org/$orgId/parts'
    | '/org/$orgId/procedures_'
    | '/org/$orgId/schedule'
    | '/org/$orgId/settings'
    | '/org/$orgId/work-orders'
    | '/app/$orgId/'
    | '/org/$orgId/'
    | '/app/$orgId/settings_/profile'
    | '/app/$orgId/work-orders/$workOrderId'
    | '/org/$orgId/procedures_/$procedureId'
    | '/org/$orgId/procedures_/create'
    | '/org/$orgId/settings/invitations'
    | '/org/$orgId/settings/members'
    | '/org/$orgId/settings/organization'
    | '/org/$orgId/settings/profile'
    | '/org/$orgId/procedures_/'
    | '/org/$orgId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStorageAuthRoute: typeof ApiStorageAuthRoute
  AppOrgIdRoute: typeof AppOrgIdRouteWithChildren
  OrgOrgIdRoute: typeof OrgOrgIdRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgId': {
      id: '/app/$orgId'
      path: '/app/$orgId'
      fullPath: '/app/$orgId'
      preLoaderRoute: typeof AppOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage-auth': {
      id: '/api/storage-auth'
      path: '/api/storage-auth'
      fullPath: '/api/storage-auth'
      preLoaderRoute: typeof ApiStorageAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/app/$orgId/': {
      id: '/app/$orgId/'
      path: '/'
      fullPath: '/app/$orgId/'
      preLoaderRoute: typeof AppOrgIdIndexRouteImport
      parentRoute: typeof AppOrgIdRoute
    }
    '/org/$orgId/work-orders': {
      id: '/org/$orgId/work-orders'
      path: '/work-orders'
      fullPath: '/org/$orgId/work-orders'
      preLoaderRoute: typeof OrgOrgIdWorkOrdersRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings': {
      id: '/org/$orgId/settings'
      path: '/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof OrgOrgIdSettingsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/schedule': {
      id: '/org/$orgId/schedule'
      path: '/schedule'
      fullPath: '/org/$orgId/schedule'
      preLoaderRoute: typeof OrgOrgIdScheduleRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/procedures_': {
      id: '/org/$orgId/procedures_'
      path: '/procedures'
      fullPath: '/org/$orgId/procedures'
      preLoaderRoute: typeof OrgOrgIdProceduresRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/parts': {
      id: '/org/$orgId/parts'
      path: '/parts'
      fullPath: '/org/$orgId/parts'
      preLoaderRoute: typeof OrgOrgIdPartsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/locations': {
      id: '/org/$orgId/locations'
      path: '/locations'
      fullPath: '/org/$orgId/locations'
      preLoaderRoute: typeof OrgOrgIdLocationsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/businesses': {
      id: '/org/$orgId/businesses'
      path: '/businesses'
      fullPath: '/org/$orgId/businesses'
      preLoaderRoute: typeof OrgOrgIdBusinessesRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/assets': {
      id: '/org/$orgId/assets'
      path: '/assets'
      fullPath: '/org/$orgId/assets'
      preLoaderRoute: typeof OrgOrgIdAssetsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/app/$orgId/settings': {
      id: '/app/$orgId/settings'
      path: '/settings'
      fullPath: '/app/$orgId/settings'
      preLoaderRoute: typeof AppOrgIdSettingsRouteImport
      parentRoute: typeof AppOrgIdRoute
    }
    '/org/$orgId/settings/': {
      id: '/org/$orgId/settings/'
      path: '/'
      fullPath: '/org/$orgId/settings/'
      preLoaderRoute: typeof OrgOrgIdSettingsIndexRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/procedures_/': {
      id: '/org/$orgId/procedures_/'
      path: '/'
      fullPath: '/org/$orgId/procedures/'
      preLoaderRoute: typeof OrgOrgIdProceduresIndexRouteImport
      parentRoute: typeof OrgOrgIdProceduresRoute
    }
    '/org/$orgId/settings/profile': {
      id: '/org/$orgId/settings/profile'
      path: '/profile'
      fullPath: '/org/$orgId/settings/profile'
      preLoaderRoute: typeof OrgOrgIdSettingsProfileRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/organization': {
      id: '/org/$orgId/settings/organization'
      path: '/organization'
      fullPath: '/org/$orgId/settings/organization'
      preLoaderRoute: typeof OrgOrgIdSettingsOrganizationRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/members': {
      id: '/org/$orgId/settings/members'
      path: '/members'
      fullPath: '/org/$orgId/settings/members'
      preLoaderRoute: typeof OrgOrgIdSettingsMembersRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/invitations': {
      id: '/org/$orgId/settings/invitations'
      path: '/invitations'
      fullPath: '/org/$orgId/settings/invitations'
      preLoaderRoute: typeof OrgOrgIdSettingsInvitationsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/procedures_/create': {
      id: '/org/$orgId/procedures_/create'
      path: '/create'
      fullPath: '/org/$orgId/procedures/create'
      preLoaderRoute: typeof OrgOrgIdProceduresCreateRouteImport
      parentRoute: typeof OrgOrgIdProceduresRoute
    }
    '/org/$orgId/procedures_/$procedureId': {
      id: '/org/$orgId/procedures_/$procedureId'
      path: '/$procedureId'
      fullPath: '/org/$orgId/procedures/$procedureId'
      preLoaderRoute: typeof OrgOrgIdProceduresProcedureIdRouteImport
      parentRoute: typeof OrgOrgIdProceduresRoute
    }
    '/app/$orgId/work-orders/$workOrderId': {
      id: '/app/$orgId/work-orders/$workOrderId'
      path: '/work-orders/$workOrderId'
      fullPath: '/app/$orgId/work-orders/$workOrderId'
      preLoaderRoute: typeof AppOrgIdWorkOrdersWorkOrderIdRouteImport
      parentRoute: typeof AppOrgIdRoute
    }
    '/app/$orgId/settings_/profile': {
      id: '/app/$orgId/settings_/profile'
      path: '/settings/profile'
      fullPath: '/app/$orgId/settings/profile'
      preLoaderRoute: typeof AppOrgIdSettingsProfileRouteImport
      parentRoute: typeof AppOrgIdRoute
    }
  }
}

interface AppOrgIdRouteChildren {
  AppOrgIdSettingsRoute: typeof AppOrgIdSettingsRoute
  AppOrgIdIndexRoute: typeof AppOrgIdIndexRoute
  AppOrgIdSettingsProfileRoute: typeof AppOrgIdSettingsProfileRoute
  AppOrgIdWorkOrdersWorkOrderIdRoute: typeof AppOrgIdWorkOrdersWorkOrderIdRoute
}

const AppOrgIdRouteChildren: AppOrgIdRouteChildren = {
  AppOrgIdSettingsRoute: AppOrgIdSettingsRoute,
  AppOrgIdIndexRoute: AppOrgIdIndexRoute,
  AppOrgIdSettingsProfileRoute: AppOrgIdSettingsProfileRoute,
  AppOrgIdWorkOrdersWorkOrderIdRoute: AppOrgIdWorkOrdersWorkOrderIdRoute,
}

const AppOrgIdRouteWithChildren = AppOrgIdRoute._addFileChildren(
  AppOrgIdRouteChildren,
)

interface OrgOrgIdProceduresRouteChildren {
  OrgOrgIdProceduresProcedureIdRoute: typeof OrgOrgIdProceduresProcedureIdRoute
  OrgOrgIdProceduresCreateRoute: typeof OrgOrgIdProceduresCreateRoute
  OrgOrgIdProceduresIndexRoute: typeof OrgOrgIdProceduresIndexRoute
}

const OrgOrgIdProceduresRouteChildren: OrgOrgIdProceduresRouteChildren = {
  OrgOrgIdProceduresProcedureIdRoute: OrgOrgIdProceduresProcedureIdRoute,
  OrgOrgIdProceduresCreateRoute: OrgOrgIdProceduresCreateRoute,
  OrgOrgIdProceduresIndexRoute: OrgOrgIdProceduresIndexRoute,
}

const OrgOrgIdProceduresRouteWithChildren =
  OrgOrgIdProceduresRoute._addFileChildren(OrgOrgIdProceduresRouteChildren)

interface OrgOrgIdSettingsRouteChildren {
  OrgOrgIdSettingsInvitationsRoute: typeof OrgOrgIdSettingsInvitationsRoute
  OrgOrgIdSettingsMembersRoute: typeof OrgOrgIdSettingsMembersRoute
  OrgOrgIdSettingsOrganizationRoute: typeof OrgOrgIdSettingsOrganizationRoute
  OrgOrgIdSettingsProfileRoute: typeof OrgOrgIdSettingsProfileRoute
  OrgOrgIdSettingsIndexRoute: typeof OrgOrgIdSettingsIndexRoute
}

const OrgOrgIdSettingsRouteChildren: OrgOrgIdSettingsRouteChildren = {
  OrgOrgIdSettingsInvitationsRoute: OrgOrgIdSettingsInvitationsRoute,
  OrgOrgIdSettingsMembersRoute: OrgOrgIdSettingsMembersRoute,
  OrgOrgIdSettingsOrganizationRoute: OrgOrgIdSettingsOrganizationRoute,
  OrgOrgIdSettingsProfileRoute: OrgOrgIdSettingsProfileRoute,
  OrgOrgIdSettingsIndexRoute: OrgOrgIdSettingsIndexRoute,
}

const OrgOrgIdSettingsRouteWithChildren =
  OrgOrgIdSettingsRoute._addFileChildren(OrgOrgIdSettingsRouteChildren)

interface OrgOrgIdRouteChildren {
  OrgOrgIdAssetsRoute: typeof OrgOrgIdAssetsRoute
  OrgOrgIdBusinessesRoute: typeof OrgOrgIdBusinessesRoute
  OrgOrgIdLocationsRoute: typeof OrgOrgIdLocationsRoute
  OrgOrgIdPartsRoute: typeof OrgOrgIdPartsRoute
  OrgOrgIdProceduresRoute: typeof OrgOrgIdProceduresRouteWithChildren
  OrgOrgIdScheduleRoute: typeof OrgOrgIdScheduleRoute
  OrgOrgIdSettingsRoute: typeof OrgOrgIdSettingsRouteWithChildren
  OrgOrgIdWorkOrdersRoute: typeof OrgOrgIdWorkOrdersRoute
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
}

const OrgOrgIdRouteChildren: OrgOrgIdRouteChildren = {
  OrgOrgIdAssetsRoute: OrgOrgIdAssetsRoute,
  OrgOrgIdBusinessesRoute: OrgOrgIdBusinessesRoute,
  OrgOrgIdLocationsRoute: OrgOrgIdLocationsRoute,
  OrgOrgIdPartsRoute: OrgOrgIdPartsRoute,
  OrgOrgIdProceduresRoute: OrgOrgIdProceduresRouteWithChildren,
  OrgOrgIdScheduleRoute: OrgOrgIdScheduleRoute,
  OrgOrgIdSettingsRoute: OrgOrgIdSettingsRouteWithChildren,
  OrgOrgIdWorkOrdersRoute: OrgOrgIdWorkOrdersRoute,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
}

const OrgOrgIdRouteWithChildren = OrgOrgIdRoute._addFileChildren(
  OrgOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStorageAuthRoute: ApiStorageAuthRoute,
  AppOrgIdRoute: AppOrgIdRouteWithChildren,
  OrgOrgIdRoute: OrgOrgIdRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
